config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', via: [:get, :post]

  # match '/auth/admin/callback', to: 'sessions#authenticate_admin', as: :google_callback, via: [:get, :post]
  # match 'auth/facebook/callback', to: 'sessions#create', as: :facebook_callback, via: [:get, :post]
  match 'auth/failure', to: redirect('/why-facebook'), as: :facebook_failure, via: [:get, :post]
  match 'logout', to: 'sessions#destroy', via: [:get, :post]
  match 'about-us', to: 'pages#about_us', via: :get
  match 'bars-and-venues', to: 'pages#bars_and_venues', via: [:get, :post]
  match 'contact-us', to: 'pages#contact_us', via: [:get, :post]
  match 'faq', to: 'pages#faq', via: :get
  match 'how-it-works', to: 'pages#how_it_works', via: :get
  match 'press', to: 'pages#press', via: :get
  match 'privacy-policy', to: 'pages#privacy_policy', via: :get
  match 'terms-of-service', to: 'pages#terms_of_service', via: :get
  match 'why-facebook', to: 'pages#why_facebook', via: :get
  match 'r/:id', to: 'user/reservations#join', as: :join_reservation, via: :get
  match 'c/:id', to: 'pages#join', as: :join_referral, via: :get
  match 'venue/confirm', to: 'venues#confirm_booking', as: :venue_confirm_booking, via: :get
  match 'venue/reject', to: 'venues#reject_booking', as: :venue_reject_booking, via: :get

  match 'facebookprivatepilot', to: redirect('/'), via: :get

  get '/login', to: 'sessions#new', as: :new_user_login
  post '/login', to: 'sessions#create', as: :user_login

  namespace :admin do
    root to: 'admins#dashboard'

    resources :applicants, only: [:index, :show] do
      collection do
        get 'accept_selected'
        get 'reject_selected'
        get 'export_applicant'
      end
      member do
        get 'accept'
        post 'accept_member'
        get 'reject'
        post 'reject_member'
        get 'block'
        post 'block_member'
      end
    end

    resources :pools, only:[:index, :show, :create] do
      member do
        get 'possible_matches'
      end
      collection do
        get 'new_grouvly'
        post 'book_grouvly'
        post 'update_reservation_date'
      end
    end

    resources :reservations do
      collection do
        post 'capture_all_payments'
        post 'refund_amount'
      end
      member do
        get 'cancel_booking'
      end
    end

    resources :members, only: [:index, :show, :edit,:update] do
      member do
        post 'create_note'
      end
      collection do
        get 'search'
      end
    end

    resources :matches, only: [:index, :show] do
      member do
        post 'unmatch'
        post 'confirm_match'
      end
      collection do
        post 'book_venues', to: 'matches#book_venues'
        post 'notify_location', to: 'matches#notify_venue_location_details'
      end
    end

    resources :venues
    resources :vouchers
  end

  namespace :user do
    root to: 'users#dashboard'

    resource :membership, only: [:new, :create, :edit, :update] do
      member do
        get 'finish'
        get 'invite'
        get 'apply'
        patch 'submit_application'
      end
    end

    resources :reservations, only: [:new, :create] do
      member do
        get 'invite_wings'
        get 'confirmed'
        get 'roll'
        get 'refund_amount'
      end
      collection do
        post 'roll_confirmed'
        get 'venue/confirm/:id', to: 'reservations#confirm_venue_notification', as: :confirm_location
      end
    end

    resource :payment, only: [:new, :create] do
      member do
        post 'validate_voucher'
      end
    end
  end

  get 'admin/login', to: 'sessions#new_admin'
  post 'admin/login', to: 'sessions#admin_login'

  scope :location, as: :location do
    get 'countries', to: 'locations#countries'
    get 'neighborhoods', to: 'locations#neighborhoods'
  end

  constraints subdomain: :blog do
    get "*all", to: redirect { |params, req| "https://grouvly.com/blog/#{params[:all]}" }
  end

  get '/blog' => redirect('https://www.grouvly.com/blog/')

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: '/2kQ1VqsGzd'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::AdminsController
  before_filter :check_member_is_valid, only: [:show]
   before_filter :get_user, only: [:show, :edit, :update]


  def index
    if params[:location]
      @presenter = ListMembersPresenter.new({ location: params[:location], gender: params[:gender],
        page: params[:page] })
    else
      @presenter = ListMembersPresenter.new
    end
  end

  def show
    @payments_with_voucher = Payment.includes(:reservation, :voucher).joins(card: :user).where(users: { id: member.id })
      .where("(payments.status = 'success' AND payments.method = 'authorize') OR payments.method IN ('capture', 'refund')")
      .where('payments.voucher_id IS NOT NULL')
  end

  def edit
    membership = @user_decorator.user.user_info
    @presenter = EditMembershipPresenter.new(membership)
  end

  def update
    errors = []
    user_info = @user_decorator.user.user_info
    if user_info.update_attributes(member_params)
      flash[:notice] = t('admin.applicants.update.success')
    else
      user_info.errors.messages.each {|key, value| errors << "#{key} : #{value.join(",")}"}
      flash[:error] = errors.join(", ")
    end
    redirect_to :back
  end

  def search
    request.format = "csv" if params[:export].present?
    @search_member_presenter = SearchMemberPresenter.new
    all_records = UserScope.filter_members(member_filter_params)
    @members = all_records.page(params[:page])
    respond_to do |format|
      format.html

      format.csv { send_data all_records.to_csv, filename: 'member_details.csv'}

      format.json { render json: (ActiveModel::ArraySerializer.new(@members, each_serializer: UserSerializer,root: 'members')).to_json }
    end
  end

  def create_note
    if params[:content].present?
      member.user_notes << UserNote.new(content: params[:content])
      unless member.save
        flash[:error] = member.errors.full_messages.to_sentence
      end
    end
    redirect_to :back
  end

  private

  def check_member_is_valid
    not_found if member.pending? || member.new?
  end

  def member
    @member ||= User.friendly.find(params[:id])
  end

  def get_user
    @user_decorator = UserDecorator.new(member)
  end

  def member_params
    params[:user_info][:meet_new_people_ages] ||= []
    params[:user_info][:neighborhoods] ||= []
    params[:user_info][:typical_weekends] ||= []
    params.require(:user_info).permit(:email_address, :gender_to_match, :location, :phone, :current_work, :studied_at, :religion, :ethnicity, :height, :current_employer, :gender, :birthday, :native_place, :hang_out_with, meet_new_people_ages:[], neighborhoods:[], typical_weekends:[])
  end

  def member_filter_params
    params.permit(:location, :gender, :age_min, :age_max, :height_min, :height_max, :ethnicity, :name, :origin, :hang_out_with, meet_new_people_ages:[], neighborhoods:[], typical_weekends:[])
  end
end

app/views/admin/members/shared/_navigation.html.slim
nav[role='navigation']
  ul.nav.nav-tabs
    li.active
      = link_to t('admin.members.show.notes'), '#user-notes', { role: 'tab', data: { toggle: 'tab' } }
    
    li
      = link_to t('admin.members.show.credit'), '#user-credits', { role: 'tab', data: { toggle: 'tab' } }
    
    li
      = link_to t('admin.members.show.vouchers'), '#user-vouchers', { role: 'tab', data: { toggle: 'tab' } }
    
    li
      = link_to t('admin.members.show.friends'), '#user-friends', { role: 'tab', data: { toggle: 'tab' } }
    
    li
      = link_to t('admin.members.show.reservations'), '#user-reservations', { role: 'tab', data: { toggle: 'tab' } }

app/views/admin/members/shared/_user_credits.html.slim
#user-credits.tab-pane
  .row
    .col-md-6
      h5= "#{t('admin.members.show.total_credit_available')}: #{user_decorator.user.available_credits}" 
    
    .col-md-6
      h5= "#{t('admin.members.show.total_credit_used')}: #{user_decorator.user.used_credits.to_i}" 

  .row.mt-15
    .col-md-12
      - if user_decorator.user.credits.any?
        - user_decorator.user.credits.each do |credit|
          .block-user-note.row
            .col-md-3.pl-0
              p
                - if credit.action == 'add'
                  = icon('plus', '', style: 'font-size: 10px;')
                - else
                  = icon('minus', '', style: 'font-size: 10px;')
  
                | &nbsp;

                = "#{credit.currency} #{credit.amount}"
            
            .col-md-3
              p= credit.activity

            .col-md-3
              - unless credit.activity == 'signup'
                - actor = credit.actor

                - if credit.actor_type == 'User'
                  p
                    = link_to "#{actor.first_name} #{actor.last_name}", admin_member_url(actor),
                      target: '_blank'
                - elsif credit.actor_type == 'Payment'
                  - schedule = actor.reservation.schedule
                  - schedule_string = schedule.strftime("%A, %B %d") 
                  - location = APP_CONFIG['fee_currency'].keys.select { |c| APP_CONFIG['fee_currency'][c] == credit.currency }

                  p
                    - if actor.reservation.is_matched?
                      = link_to schedule_string, admin_match_path({ id: location, date: schedule }),
                        target: '_blank'
                    - else
                      = link_to schedule_string, admin_pool_path({ id: location, date: schedule }),
                        target: '_blank'

            .col-md-3.pr-0.text-right
              = time_ago_in_words(credit.created_at)

app/views/admin/members/shared/_user_friends.html.slim
#user-friends.tab-pane
  - friends.in_groups_of(2) do |friends|
    .row.mt-15
      .container-fluid
        - friends.each do |friend|
          - if friend.present?
            .col-md-6
              .media
                .media-left.media-middle
                  = link_to friend.large_profile_picture, class: "img-colorbox img-circle friend-#{friend.slug}"
                    = image_tag friend.small_profile_picture, class: 'img-circle', height: 50
                  
                  - if friend.photos.present?
                    - friend.photos.each do |photo|
                      = link_to '', photo, class: "img-colorbox user-#{friend.slug}"

                .media-body
                  - if friend.accepted?
                    = link_to "#{friend.first_name} #{friend.last_name}", admin_member_path(friend.id)
                  - else
                    = "#{friend.first_name} #{friend.last_name}"

app/views/admin/members/shared/_user_notes.html.slim
#user-notes.tab-pane.active
  = form_tag create_note_admin_member_path(user_decorator.user.id), class: 'clearfix'
    = error_messages!(user_decorator.user)

    .form-group
      = label_tag :content, t('admin.members.show.notes'), { class: 'sr-only' }
      
      = text_area_tag :content, (params[:content] if params[:content]), { class: 'form-control input-lg',
        required: true }
    
    .form-group
      = submit_tag t('admin.members.show.submit'), class: 'btn btn-primary pull-right'

  .block-user-notes
    - if user_decorator.user.user_notes.any?
      - user_decorator.user.user_notes.each do |note|
        .block-user-note.row
          .col-md-8.pl-0
            p= note.content
          
          .col-md-4.pr-0.text-right
            = time_ago_in_words(note.created_at)

app/views/admin/members/shared/_user_reservations.html.slim
#user-reservations.tab-pane
  .row
    .col-md-6
      h5= "#{t('admin.members.show.total_count')}: #{user.total_reservations}"

    .col-md-6
      h5= "#{t('admin.members.show.total_amount')}: #{user.total_reservation_amount.to_i}"

  .row.mt-15
    .col-md-12
      - if user.valid_reservations.any?
        - user.valid_reservations.each do |reservation|
          .block-user-note.row
            .col-md-1.pl-0
              p
                - if reservation.user == user
                  = 'lead'
                - else
                  = 'wing'
            .col-md-5
              p
                div.reservation_email
                  = 'lead_member :: ' + reservation.reservation_emails
                -if reservation.wings.present?
                  div.reservation_email
                    = 'wingmen/wingwomen :: ' + reservation.reservation_wing_emails

            .col-md-2
              p
                - if reservation.cancelled?
                  = 'cancelled'
                - else
                  - if reservation.is_matched?
                    - if reservation.matched_reservations.in_state(:completed).any? || reservation.inverse_matched_reservations.in_state(:completed).any?
                      = 'completed'
                    - else
                      = 'matched'
                  -else
                    = 'unmatched'
            .col-md-2
              p
                - schedule = reservation.schedule.strftime("%A, %B %d")
                - currency = reservation.all_valid_payments.first.currency
                - location = APP_CONFIG['fee_currency'].keys.select { |c| APP_CONFIG['fee_currency'][c] == currency }

                - if reservation.cancelled?
                  = schedule
                - else
                  - if reservation.is_matched?
                    = link_to schedule, admin_match_path({ id: location, date: reservation.schedule }),
                      target: '_blank'
                  - else
                    = link_to schedule, admin_pool_path({ id: location, date: reservation.schedule }),
                      target: '_blank'

            .col-md-2.pr-0.text-right
              = time_ago_in_words(reservation.created_at)

app/views/admin/members/shared/_user_vouchers.html.slim
#user-vouchers.tab-pane
  .row
    .col-md-12
      h5= "#{t('admin.members.show.total_vouchers_used')}: #{user_decorator.user.total_vouchers}"

  .row.mt-15
    .col-md-12
      - if @payments_with_voucher.any?
        - @payments_with_voucher.each do |payment|
          - voucher = payment.voucher

          .block-user-note.row
            .col-md-3.pl-0
              p= link_to voucher.try(:slug), admin_voucher_url(voucher)

            .col-md-3
              p
                - amount = voucher.amount.to_i

                - if voucher.voucher_type == 'cash'
                  = "#{payment.currency}#{amount}"
                - else
                  = "#{amount}%"

            .col-md-3
              - reservation = payment.reservation
              - schedule = reservation.schedule
              - schedule_string = schedule.strftime("%A, %B %d")
              - location = APP_CONFIG['fee_currency'].keys.select { |c| APP_CONFIG['fee_currency'][c] == payment.currency }

              p
                - if reservation.is_matched?
                  = link_to schedule_string, admin_match_path({ id: location, date: schedule }),
                    target: '_blank'
                - else
                  = link_to schedule_string, admin_pool_path({ id: location, date: schedule }),
                    target: '_blank'

            .col-md-3.pr-0.text-right
              = time_ago_in_words(payment.created_at)