config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', via: [:get, :post]

  # match '/auth/admin/callback', to: 'sessions#authenticate_admin', as: :google_callback, via: [:get, :post]
  # match 'auth/facebook/callback', to: 'sessions#create', as: :facebook_callback, via: [:get, :post]
  match 'auth/failure', to: redirect('/why-facebook'), as: :facebook_failure, via: [:get, :post]
  match 'logout', to: 'sessions#destroy', via: [:get, :post]
  match 'about-us', to: 'pages#about_us', via: :get
  match 'bars-and-venues', to: 'pages#bars_and_venues', via: [:get, :post]
  match 'contact-us', to: 'pages#contact_us', via: [:get, :post]
  match 'faq', to: 'pages#faq', via: :get
  match 'how-it-works', to: 'pages#how_it_works', via: :get
  match 'press', to: 'pages#press', via: :get
  match 'privacy-policy', to: 'pages#privacy_policy', via: :get
  match 'terms-of-service', to: 'pages#terms_of_service', via: :get
  match 'why-facebook', to: 'pages#why_facebook', via: :get
  match 'r/:id', to: 'user/reservations#join', as: :join_reservation, via: :get
  match 'c/:id', to: 'pages#join', as: :join_referral, via: :get
  match 'venue/confirm', to: 'venues#confirm_booking', as: :venue_confirm_booking, via: :get
  match 'venue/reject', to: 'venues#reject_booking', as: :venue_reject_booking, via: :get

  match 'facebookprivatepilot', to: redirect('/'), via: :get

  get '/login', to: 'sessions#new', as: :new_user_login
  post '/login', to: 'sessions#create', as: :user_login

  namespace :admin do
    root to: 'admins#dashboard'

    resources :applicants, only: [:index, :show] do
      collection do
        get 'accept_selected'
        get 'reject_selected'
        get 'export_applicant'
      end
      member do
        get 'accept'
        post 'accept_member'
        get 'reject'
        post 'reject_member'
        get 'block'
        post 'block_member'
      end
    end

    resources :pools, only:[:index, :show, :create] do
      member do
        get 'possible_matches'
      end
      collection do
        get 'new_grouvly'
        post 'book_grouvly'
        post 'update_reservation_date'
      end
    end

    resources :reservations do
      collection do
        post 'capture_all_payments'
        post 'refund_amount'
      end
      member do
        get 'cancel_booking'
      end
    end

    resources :members, only: [:index, :show, :edit,:update] do
      member do
        post 'create_note'
      end
      collection do
        get 'search'
      end
    end

    resources :matches, only: [:index, :show] do
      member do
        post 'unmatch'
        post 'confirm_match'
      end
      collection do
        post 'book_venues', to: 'matches#book_venues'
        post 'notify_location', to: 'matches#notify_venue_location_details'
      end
    end

    resources :venues
    resources :vouchers
  end

  namespace :user do
    root to: 'users#dashboard'

    resource :membership, only: [:new, :create, :edit, :update] do
      member do
        get 'finish'
        get 'invite'
        get 'apply'
        patch 'submit_application'
      end
    end

    resources :reservations, only: [:new, :create] do
      member do
        get 'invite_wings'
        get 'confirmed'
        get 'roll'
        get 'refund_amount'
      end
      collection do
        post 'roll_confirmed'
        get 'venue/confirm/:id', to: 'reservations#confirm_venue_notification', as: :confirm_location
      end
    end

    resource :payment, only: [:new, :create] do
      member do
        post 'validate_voucher'
      end
    end
  end

  get 'admin/login', to: 'sessions#new_admin'
  post 'admin/login', to: 'sessions#admin_login'

  scope :location, as: :location do
    get 'countries', to: 'locations#countries'
    get 'neighborhoods', to: 'locations#neighborhoods'
  end

  constraints subdomain: :blog do
    get "*all", to: redirect { |params, req| "https://grouvly.com/blog/#{params[:all]}" }
  end

  get '/blog' => redirect('https://www.grouvly.com/blog/')

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: '/2kQ1VqsGzd'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < Admin::AdminsController
  after_action -> { email_booked_venues(@bookings) }, only: :book_venues

  def index
    if params[:location]
      @presenter = ListMatchesPresenter.new({ location: params[:location] })
    else
      @presenter = ListMatchesPresenter.new
    end
  end

  def show
    @presenter = ShowMatchPresenter.new(location, schedule, matched_reservations)
  end

  def unmatch
    if matched_reservation.unmatch!(current_admin)
      flash[:notice] = t('admin.matches.show.unmatch_successfully')
    else
      flash[:error] = t('admin.matches.show.unmatch_wrongfully')
    end

    redirect_to :back
  end

  def confirm_match
    if matched_reservation.current_state == "completed"
      flash[:notice] = t('admin.matches.show.matched_successfully')
    else
      if matched_reservation.complete!(current_admin)
        flash[:notice] = t('admin.matches.show.confirm_match_successfully')
      else
        flash[:error] = t('admin.matches.show.confirm_match_wrongfully')
      end
    end
    redirect_to :back
  end

  def book_venues
    @bookings = []
    venue_booking_params.each do |reservation_id, venue_booking|
      if venue_booking[:venue].present? && venue_booking[:schedule].present?

        existing_booking = VenueBooking.active_bookings.where({matched_reservation_id: reservation_id}).first
        if existing_booking
          if existing_booking.venue_id != venue_booking[:venue].to_i || existing_booking.schedule != venue_booking[:schedule]
            existing_booking.cancel!
          else
            next
          end
        end

        @venue_booking = VenueBooking.new
        @venue_booking.matched_reservation_id = reservation_id
        @venue_booking.venue_id = venue_booking[:venue]
        @venue_booking.schedule = venue_booking[:schedule]
        if @venue_booking.save
          @venue_booking.new!
          @venue_booking.accept! # This is for portfolio setup
          @bookings << @venue_booking
        else
          flash[:error] = @venue_booking.errors.full_messages.first
        end

      end
    end

    if @bookings.any?
      flash[:notice] = t('admin.matches.show.book_venues_successfully', { count: @bookings.length })
    else
      flash[:error] = t('admin.matches.show.book_venues_wrongfully')
    end

    redirect_to :back
  end

  def notify_venue_location_details
    notifications = []

    matched_reservations.each do |matched_reservation|
      venue_booking = matched_reservation.latest_accepted_booking
      if venue_booking.present?
        [matched_reservation.first_reservation_id, matched_reservation.second_reservation_id].each do |reservation|

          existing_venue_notification = VenueBookingNotification
                                                  .where(venue_booking_id: venue_booking.id,
                                                         matched_reservation_id: matched_reservation.id,
                                                         reservation_id: reservation).first

          unless existing_venue_notification
            venue_booking_notification = VenueBookingNotification.new
            venue_booking_notification.venue_booking_id = venue_booking.id
            venue_booking_notification.matched_reservation_id = matched_reservation.id
            venue_booking_notification.reservation_id = reservation

            if venue_booking_notification.save
              SendVenueLocationDetailsJob.perform_now(venue_booking_notification.id)
              notifications << venue_booking_notification
            end
          end

        end
      end
    end

    if notifications.any?
      flash[:notice] = t('admin.matches.show.send_location_details_successfully', { count: notifications.length/2 })
    else
      flash[:error] = t('admin.matches.show.send_location_details_wrongfully')
    end

    redirect_to :back
  end

  private

  def location
    params[:id] || params[:location]
  end

  def schedule
    params[:date]
  end

  def matched_reservations
    @matched_reservations ||= MatchedReservation.in_state(:new, :completed).find_by_location(location).find_by_schedule(schedule).page(params[:page])
  end

  def matched_reservation
    MatchedReservation.find(params[:id])
  end

  def venue_booking_params
    params.require(:venue_booking)
  end

  def email_booked_venues(bookings)
    if bookings.any?
      # Group multiple bookings for the same venue into a single email
      venues = bookings.collect { |booking| booking.venue_id }.uniq
      venues.each do |venue|
        venue_bookings = bookings.select { |booking| booking.venue_id == venue }
        SendVenueTableBookingJob.perform_now(venue, venue_bookings)
      end
    end
  end
end

app/views/admin/matches/_block_user_column.html.slim
- is_wing ||= is_wing || false
- user_reservation = UserReservationDecorator.new(user, reservation)
- payment = user_reservation.payment

.block-user-column
  - if is_wing
    .media.is-wing
      .media-left
        = render partial: 'shared/user_image', locals: { user: user, css: 'img-rounded', width: '30' }

      .media-body
        = render partial: '/admin/matches/user_details', locals: { user: user, payment: payment, reservation: reservation, is_wing:  is_wing}
  - else
    = render partial: '/admin/matches/user_details', locals: { user: user, payment: payment, reservation: reservation, is_wing:  is_wing }

app/views/admin/matches/_content_header.html.slim
header.content-header-block
  .row
    .title-block.col-sm-6
      h1
        span= t('admin.terms.grouvly')
        small= t('admin.matches.show.title_list_by_location')
    .action-block.col-sm-6
      = content_for :header_actions

app/views/admin/matches/_user_details.html.slim
span.user-name= link_to user.name, admin_member_path(user.id)

span.label.label-default= [user.neighborhoods].join(",")

- if payment
  - if payment.status == 'error'
    span.label.label-danger= "#{payment.currency} #{payment.amount.to_f}"
  - else
    span.label.label-success= "#{payment.currency} #{payment.amount.to_f}"

  span.label.label-default= payment.transaction_id

- if reservation && reservation.venue_booking_notifications.present?
  span.venue-notification-status
    i.fa.fa-envelope class=(reservation.venue_booking_notifications.first.acknowledged ? 'is-accepted' : 'is-pending')

app/views/admin/matches/index.html.slim
= render partial: 'admin/matches/content_header'

.block-content
  .row
    .container-fluid
      .col-md-12
        h1= "#{@presenter.location} #{t('admin.matches.index.matches')}"

        table.table.table-bordered
          thead
            tr
              th
                = link_to admin_matches_path do
                  = icon('chevron-left')
                  = t('admin.matches.index.all_matches')
              th.text-uppercase= t('admin.matches.index.matches')

          tbody
            - @presenter.matches.each do |match|
              tr
                td.text-left
                  - if @presenter.location
                    = link_to "#{match[:date].strftime('%d %b %Y (%a) at %l:%M %p')}",
                      admin_match_path({ id: match[:location], date: match[:date] })
                  - else
                    = link_to match[:location], admin_matches_path({ location: match[:location] })

                td= match[:matched] 
             
            tr.background-gray
              td
              td= @presenter.total_matches

app/views/admin/matches/show.html.slim
- content_for :header_actions do
  = form_tag book_venues_admin_matches_path, method: :post, id: 'form_book_venues', class: 'pull-right' do
    = submit_tag t('admin.matches.show.book_venues'), class: 'btn btn-primary'

  = form_tag notify_location_admin_matches_path, method: :post, id: 'form_notify_location_details', class: 'pull-right' do
    = hidden_field_tag :location, @presenter.location
    = hidden_field_tag :date, @presenter.schedule
    = submit_tag t('admin.matches.show.location_details'), class: 'btn btn-primary'

= render partial: 'admin/matches/content_header'

= render partial: 'admin/shared/flash_messages'

.block-content
  .container-fluid
    .row
      .col-md-12
        - if @presenter.matched_reservations.any?
          - @presenter.matched_reservations.each do |matched_reservation|
            .row.block-reservation
              header.clearfix
                .col-md-8
                  .row
                    .col-md-5.pr-0
                      = select_tag "venue_booking[#{matched_reservation.id}][venue]",
                        options_for_select(@presenter.available_venues, (matched_reservation.latest_booking.venue_id if matched_reservation.latest_booking)),
                          include_blank: true, form: 'form_book_venues', class: 'form-control'

                    .col-md-3
                      = select_tag "venue_booking[#{matched_reservation.id}][schedule]",
                        options_for_select(@presenter.available_time_slots, (if matched_reservation.latest_booking then matched_reservation.latest_booking.schedule else @presenter.schedule end)), form: 'form_book_venues', class: 'form-control'

                    - if matched_reservation.latest_booking
                      .col-md-1.block-booking-status
                        - if matched_reservation.latest_booking.accepted?
                          i.fa.fa-clock-o.is-accepted
                        - elsif matched_reservation.latest_booking.rejected?
                          i.fa.fa-clock-o.is-rejected
                        - else
                          i.fa.fa-clock-o.is-pending

                    - venue_notifications = matched_reservation.venue_booking_notifications

                    - if venue_notifications.present?
                      .col-md-1.venue-notification-status
                        - if venue_notifications.all? { |venue_notification| venue_notification.acknowledged == true }
                          i.fa.fa-envelope.is-accepted
                        - else
                          i.fa.fa-envelope.is-pending

                .col-md-2
                  = form_tag unmatch_admin_match_path(matched_reservation), method: :post, class: 'pull-right form_unmatch' do
                    = hidden_field_tag :matched_reservation_id, matched_reservation.id
                    = submit_tag t('admin.matches.show.unmatch'), class: 'btn btn-link pull-right'
                .col-md-2
                  = form_tag confirm_match_admin_match_path(matched_reservation), method: :post, class: 'pull-right confirm_match_btn' do
                    = submit_tag  t('admin.matches.show.confirm_match'), class: 'btn btn-link pull-right'

                  /
                    =link_to t('admin.matches.show.confirm_match'), confirm_match_admin_match_path(matched_reservation), class: "btn btn-link pull-right confirm_match_btn"

              .col-md-12.clearfix
                - [:first_reservation, :second_reservation].each do |index|
                  - reservation = matched_reservation.send(index)
                  - lead = reservation.user

                  .col-md-6.user-list-card
                    .block-image
                      = render partial: 'shared/user_image', locals: { user: lead, css: 'img-rounded',
                        width: '110' }

                    .block-body
                      = render partial: '/admin/matches/block_user_column', locals: { user: lead,
                        reservation: reservation }

                      - if reservation.wings.count > 0
                        - reservation.wings.each do |wing|
                          = render partial: '/admin/matches/block_user_column', locals: {user: wing,
                            is_wing: true, reservation: reservation }

                      .row
                        .container-fluid
                          = "ID: #{reservation.id}"

                      - if !reservation.pending_payment? && reservation.all_due_payments.count == 0  && Chronic.parse('now') >= reservation.schedule + 7.days
                        .row.block-actions
                          .container-fluid
                            - reservation_payment_scope = ReservationPaymentScope.new(reservation)
                            = form_tag refund_amount_admin_reservations_path, method: :post do

                              .block-user-column
                                .row
                                  .col-sm-4
                                    = select_tag "member_id", options_from_collection_for_select(reservation_payment_scope.available_members, "id", "name"), prompt: "Member", class: 'form-control'

                                  .col-sm-5.left-padding
                                    = text_field_tag :refund_amount, nil, placeholder: t("admin.matches.show.refund_amount_placeholder"), class: 'form-control'
                                    = hidden_field_tag :id, reservation.slug

                                  .col-sm-3.left-padding
                                    = submit_tag t('admin.matches.show.refund'), class: 'btn btn-transparent'
                      -elsif reservation.all_due_payments.count > 0
                        .row.block-actions
                          .container-fluid
                            = form_tag capture_all_payments_admin_reservations_path, method: :post do
                              = hidden_field_tag :id, reservation.slug
                              = submit_tag t('admin.matches.show.capture'), class: 'btn btn-transparent btn-capture'
                      -elsif reservation.pending_payment?
                        .row.block-actions
                          .container-fluid
                            span.label.label-danger Pending Payment!

        - else
          p.text-center.mt-20= t('admin.matches.no_matches')

  .row
    .col-md-12.text-center= paginate @presenter.matched_reservations