config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', via: [:get, :post]

  # match '/auth/admin/callback', to: 'sessions#authenticate_admin', as: :google_callback, via: [:get, :post]
  # match 'auth/facebook/callback', to: 'sessions#create', as: :facebook_callback, via: [:get, :post]
  match 'auth/failure', to: redirect('/why-facebook'), as: :facebook_failure, via: [:get, :post]
  match 'logout', to: 'sessions#destroy', via: [:get, :post]
  match 'about-us', to: 'pages#about_us', via: :get
  match 'bars-and-venues', to: 'pages#bars_and_venues', via: [:get, :post]
  match 'contact-us', to: 'pages#contact_us', via: [:get, :post]
  match 'faq', to: 'pages#faq', via: :get
  match 'how-it-works', to: 'pages#how_it_works', via: :get
  match 'press', to: 'pages#press', via: :get
  match 'privacy-policy', to: 'pages#privacy_policy', via: :get
  match 'terms-of-service', to: 'pages#terms_of_service', via: :get
  match 'why-facebook', to: 'pages#why_facebook', via: :get
  match 'r/:id', to: 'user/reservations#join', as: :join_reservation, via: :get
  match 'c/:id', to: 'pages#join', as: :join_referral, via: :get
  match 'venue/confirm', to: 'venues#confirm_booking', as: :venue_confirm_booking, via: :get
  match 'venue/reject', to: 'venues#reject_booking', as: :venue_reject_booking, via: :get

  match 'facebookprivatepilot', to: redirect('/'), via: :get

  get '/login', to: 'sessions#new', as: :new_user_login
  post '/login', to: 'sessions#create', as: :user_login

  namespace :admin do
    root to: 'admins#dashboard'

    resources :applicants, only: [:index, :show] do
      collection do
        get 'accept_selected'
        get 'reject_selected'
        get 'export_applicant'
      end
      member do
        get 'accept'
        post 'accept_member'
        get 'reject'
        post 'reject_member'
        get 'block'
        post 'block_member'
      end
    end

    resources :pools, only:[:index, :show, :create] do
      member do
        get 'possible_matches'
      end
      collection do
        get 'new_grouvly'
        post 'book_grouvly'
        post 'update_reservation_date'
      end
    end

    resources :reservations do
      collection do
        post 'capture_all_payments'
        post 'refund_amount'
      end
      member do
        get 'cancel_booking'
      end
    end

    resources :members, only: [:index, :show, :edit,:update] do
      member do
        post 'create_note'
      end
      collection do
        get 'search'
      end
    end

    resources :matches, only: [:index, :show] do
      member do
        post 'unmatch'
        post 'confirm_match'
      end
      collection do
        post 'book_venues', to: 'matches#book_venues'
        post 'notify_location', to: 'matches#notify_venue_location_details'
      end
    end

    resources :venues
    resources :vouchers
  end

  namespace :user do
    root to: 'users#dashboard'

    resource :membership, only: [:new, :create, :edit, :update] do
      member do
        get 'finish'
        get 'invite'
        get 'apply'
        patch 'submit_application'
      end
    end

    resources :reservations, only: [:new, :create] do
      member do
        get 'invite_wings'
        get 'confirmed'
        get 'roll'
        get 'refund_amount'
      end
      collection do
        post 'roll_confirmed'
        get 'venue/confirm/:id', to: 'reservations#confirm_venue_notification', as: :confirm_location
      end
    end

    resource :payment, only: [:new, :create] do
      member do
        post 'validate_voucher'
      end
    end
  end

  get 'admin/login', to: 'sessions#new_admin'
  post 'admin/login', to: 'sessions#admin_login'

  scope :location, as: :location do
    get 'countries', to: 'locations#countries'
    get 'neighborhoods', to: 'locations#neighborhoods'
  end

  constraints subdomain: :blog do
    get "*all", to: redirect { |params, req| "https://grouvly.com/blog/#{params[:all]}" }
  end

  get '/blog' => redirect('https://www.grouvly.com/blog/')

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: '/2kQ1VqsGzd'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/concerns/admin/payments.rb
module Admin::Payments
  extend ActiveSupport::Concern

  private

  def payment_params
    params.require(:payment).permit(:name, :voucher_code, reservation_attributes: [:schedule, :id, :last_minute_booking])
  end

  def only_payment_params
    payment_params.except(:reservation_attributes)
  end

  def get_payment_with_reservation
    payment = Payment.new(only_payment_params)
    payment.reservation = Reservation.find(payment_params[:reservation_attributes][:id])
    payment
  end

  def payment
    @payment ||= if params[:payment]
      get_payment_with_reservation
    else
      Payment.new({ reservation: new_reservation })
    end
  end

  def build_schedule
    reservation = @user.reservations.active.where(schedule: params[:schedule]).first

    reservation = @user.reservations.build({ schedule: params[:schedule], user_type: "admin" }) if reservation.blank?

    reservation.update_attribute("user_type", "admin")
    reservation
  end

  def new_reservation
    @reservation ||= if params[:schedule]
      build_schedule
    end
  end

  def payment_collector
    @payment_collector ||= PaymentCollector.new(@user, payment)
  end

  def set_other_payment_info
    payment.amount = @new_payment_presenter.fee
    payment.currency = @new_payment_presenter.currency
    payment.user = @user
    payment.name = @user.name
    if @user.valid_cards.present?
      payment.card = @user.active_card
      payment.status = "success"
    else
      payment.status = "pending"
    end
  end

  def send_emails
    if reservation.user == @user
      if payment.status == "success"
        SendLeadPaymentEmailJob.perform_now(payment.id)
        SendForwardToFriendsEmailJob.perform_now(payment.id)
      elsif payment.status == "pending"
        SendPendingPaymentEmailJob.perform_now(payment.id)
      end
    end
  end
end

app/controllers/concerns/user/membership_authorizations.rb
module User::MembershipAuthorizations
  extend ActiveSupport::Concern

  included do
    skip_before_filter :check_membership_info, only: [:new, :create]
    skip_before_filter :check_user_pending, only: [:finish, :invite, :edit, :update, :neighborhoods]
    skip_before_filter :check_user_rejected, only: [:finish, :invite, :edit, :update, :neighborhoods]

    before_filter :check_membership_info_exists, only: [:new, :create]
    before_filter :check_membership_rejected_or_pending, only: [:finish]
    before_filter :check_membership_wing, only: [:apply, :submit_application]
  end

  private

  def check_membership_info_exists
    redirect_to user_root_url and return if current_user.user_info.present?
    # redirect_to user_root_url and return unless current_user.new?
  end

  def check_membership_rejected_or_pending
    redirect_to user_root_url and return if current_user.accepted? || current_user.wing?
  end

  def check_membership_wing
    redirect_to user_root_url and return unless current_user.wing?
  end
end

app/controllers/concerns/user/memberships.rb
module User::Memberships
  extend ActiveSupport::Concern

  private

  def membership_params
    unless params[:continue]
      params[:user_info][:meet_new_people_ages] ||= []
      params[:user_info][:neighborhoods] ||= []
      params[:user_info][:typical_weekends] ||= []
    end
    params.require(:user_info).permit(:email_address, :gender_to_match, :location, :phone, :current_work,
      :studied_at, :religion, :ethnicity, :height, :current_employer, :gender, :birthday, :native_place, :hang_out_with, meet_new_people_ages:[], neighborhoods:[], typical_weekends:[])
  end

  def membership
    @membership ||= if current_user.user_info.present?
      current_user.user_info.assign_attributes(membership_params) if params[:user_info]
      current_user.user_info
    elsif params[:user_info]
      current_user.build_user_info(membership_params)
    else
      current_user.build_user_info
    end
  end

  def continue_with_step_two
    if membership.errors.blank?
      # membership.set_gender(me)
      # membership.set_birthday(me)
      # membership.set_work(me)
      # membership.set_education(me)
      @step_two_membership_presenter = StepTwoMembershipPresenter.new(membership)
      render 'step_two'
    else
      @new_membership_presenter = NewMembershipPresenter.new(membership)
      render 'new'
    end
  end

  def set_user_as_wing
    current_user.wing!
    url = session.delete(:join_grouvly_url).split('/').last
    url = new_user_payment_url({ reservation: url })
    redirect_to url
  end

  def set_user_as_pending
    current_user.pend!
    redirect_to finish_user_membership_url
  end

  def finish_submitting_membership
    membership.set_other_details(nil, nil, params[:user_info])  #for portfolio project
    # membership.set_other_details(me, graph, params[:user_info])
    membership.update_images
    if session[:join_grouvly_url]
      membership.save!(validate: false)
      set_user_as_wing
    else
      membership.save!
      set_user_as_pending
    end
  end

  def get_parameters_for_update
    parameters = membership_params
    parse_birthday(parameters)
    # if membership_params[:neighborhood] == t('terms.others')
    #   parameters[:neighborhood] = membership_params[:other_neighborhood]
    # end
    # if membership_params[:native_place] == t('terms.others')
    #   parameters[:native_place] = membership_params[:other_native_place]
    # end
    country = Carmen::Country.coded(parameters[:native_place])
    if country.present?
      parameters[:origin] = parameters[:location] == country.name ? APP_CONFIG['available_origins']['local'] : APP_CONFIG['available_origins']['expat']
    else
      parameters[:origin] = APP_CONFIG['available_origins']['expat']
    end
    parameters
  end

  def parse_birthday(parameters)
    birthday_hash = {
      1 => parameters.delete(:"birthday(1i)"),
      2 => parameters.delete(:"birthday(2i)"),
      3 => parameters.delete(:"birthday(3i)")
    }
    parameters[:birthday] = Date.new(birthday_hash[1].to_i, birthday_hash[2].to_i, birthday_hash[3].to_i)
    parameters
  end

  def prepare_edit_presenter
    @presenter = EditMembershipPresenter.new(membership)
    #@presenter.set_neighborhood
    current_user.reload
  end
end

app/controllers/concerns/user/payment_authorizations.rb
module User::PaymentAuthorizations
  extend ActiveSupport::Concern

  included do
    skip_before_filter :check_user_blocked
    skip_before_filter :check_user_rejected
    skip_before_filter :check_user_deauthorized
    skip_before_filter :check_user_pending
    before_filter :check_reservation_date, except: [:validate_voucher]
    before_filter :check_reservation_is_full, except: [:validate_voucher]
    before_filter :check_user_already_has_reservation, except: [:validate_voucher]
    before_filter :check_user_same_gender, except: [:validate_voucher]
    before_filter :check_if_user_can_make_new_payments, except: [:validate_voucher]
  end

  private

  def check_reservation_date
    if schedule
      user_type = "admin" if reservation.last_minute_booking
      if ((Grouvly::ReservationDate.is_schedule_with_most_recent_valid?(schedule) &&
        schedule < Chronic.parse('now') && current_user != reservation.user) ||
        (!Grouvly::ReservationDate.is_schedule_valid?(schedule, user_type) && current_user == reservation.user))
        flash[:error] = t('user.reservations.errors.messages.you_have_not_chosen_a_valid_schedule')
        redirect_to new_user_reservation_url and return
      end
    else
      render not_found
    end
  end

  def check_reservation_is_full
    if reservation.is_full?
      flash[:error] = t('user.reservations.errors.messages.this_grouvly_date_is_already_full')
      redirect_to new_user_reservation_url and return
    end
  end

  def check_user_already_has_reservation
    if payment.status != "pending"
      if current_user.has_paid_reservation_on?(schedule)
        flash[:error] = I18n.t('user.payments.errors.paid_reservation_exists_error')
        redirect_to new_user_reservation_url and return
      end
    end
  end

  def check_user_same_gender
    user = reservation.user

    if !reservation.new_record? && !current_user.has_same_gender_as?(user)
      user_decorator = UserDecorator.new(user)
      flash[:error] = I18n.t('user.payments.errors.needs_proper_wing_gender', user: user.first_name,
        wing: user_decorator.wing_type)
      redirect_to join_reservation_url(reservation.slug) and return
    end
  end

  def check_if_user_can_make_new_payments
    redirect_to finish_user_membership_url and return if reservation.new_record? && !current_user.accepted?
  end
end

app/controllers/concerns/user/payments.rb
module User::Payments
  extend ActiveSupport::Concern

  private

  def payment_params
    params.require(:payment).permit(:name, :voucher_code, reservation_attributes: [:schedule, :id, :wing_quantity])
  end

  def only_payment_params
    payment_params.except(:reservation_attributes)
  end

  def get_payment_with_reservation
    payment = Payment.new(only_payment_params)
    payment.reservation = Reservation.find(payment_params[:reservation_attributes][:id])
    payment
  end

  def payment
    @payment ||= if params[:payment]
      get_payment_with_reservation
    else
      Payment.new({ reservation: reservation })
    end
  end

  def build_schedule
    render not_found and return unless current_user.accepted?

    reservation = current_user.reservations.active.where(schedule: params[:schedule]).first

    if reservation.blank?
      reservation = current_user.reservations.build({ schedule: params[:schedule]})

      if reservation.save
        return reservation
      else
        flash.now[:error] = I18n.t('user.reservations.cannot_process_payment')
        redirect_to new_user_reservation_url
      end
    else
      return reservation
    end
  end

  def reservation
    @reservation ||= if params[:schedule]
      build_schedule
    elsif params[:reservation]
      Reservation.where(slug: params[:reservation]).first
    elsif params[:payment]
      Reservation.find(params[:payment][:reservation_attributes][:id])
    end

    if @reservation.blank?
      render not_found
    else
      if params[:payment] && params["payment"]["reservation_attributes"]["wing_quantity"]
        @reservation.update_attribute("wing_quantity", params["payment"]["reservation_attributes"]["wing_quantity"])
      end
      @reservation.update_attribute("last_minute_booking", true) if is_last_minute_booking?(@reservation.schedule)
      @reservation
    end
  end

  def is_last_minute_booking?(upcoming_date)
    if upcoming_date.present?
      upcoming_date = upcoming_date
      before_48_hours = upcoming_date - 48.hours
      before_4_hours = upcoming_date - 4.hours
      current_time = Chronic.parse('now')
      current_time >= before_48_hours && current_time < before_4_hours
    else
      false
    end
  end

  def schedule
    schedule = if reservation
      reservation.schedule
    elsif params[:payment]
      params[:payment][:reservation_attributes][:schedule]
    end
  end

  def user_type
    user_type = if reservation
      reservation.user_type
    elsif params[:payment]
      params[:payment][:reservation_attributes][:user_type]
    end
  end

  def payment_collector
    @payment_collector ||= PaymentCollector.new(current_user, payment)
  end

  def set_other_payment_info
    BRAINTREE_LOGGER.info("payment_method_nonce :: #{params[:payment_method_nonce]}")
    @reservation.update_attribute(:last_minute_booking, true) if @new_payment_presenter.last_minute_booking
    payment.payment_method_nonce = params[:payment_method_nonce]
    payment.amount = fee
    payment.currency = @new_payment_presenter.currency
    payment.user = current_user
  end

  def fee
    @fee = if voucher.present?
      voucher_decorator.fee
    else
      @reservation.last_minute_booking ? @new_payment_presenter.total_fee : @new_payment_presenter.payment_fee
    end
    @fee
  end

  def voucher
    voucher = Voucher.where(slug: params[:payment][:voucher_code]).first if params[:payment][:voucher_code].present?
  end

  def voucher_decorator
    @user_voucher_decorator = UserVoucherDecorator.new(current_user, voucher, @reservation.last_minute_booking)
  end

  def send_emails
    if reservation.user == current_user
      SendLeadPaymentEmailJob.perform_now(payment.id)
      SendForwardToFriendsEmailJob.perform_now(payment.id)
      redirect_to invite_wings_user_reservation_url(reservation.slug) and return
    else
      SendWingPaymentEmailJob.perform_now(payment.id)
      redirect_to confirmed_user_reservation_url(reservation.slug) and return
    end
  end
end

app/controllers/concerns/user/venue_notifications.rb
module User::VenueNotifications
  extend ActiveSupport::Concern

  included do
    before_filter :check_venue_notification_is_valid, only: :confirm_venue_notification
  end

  def venue_notification
    if params[:id]
      VenueBookingNotification.where(slug: params[:id]).first
    end
  end

  private

  def check_venue_notification_is_valid
    render not_found unless params[:id].present?
  end
end

app/views/user/payments/_cancellation.html.slim
#block-cancellation
  .col-sm-3.hidden-xs &nbsp;

  .col-sm-9.text-center
    h5.text-center= t('user.payments.cancellation_policy')
    = t('user.payments.cancellation_statement')

app/views/user/payments/_form.html.slim
- unless @new_payment_presenter.fee == 0
  .form-group
    = f.label :name, t('user.payments.name'), class: 'col-sm-3 text-right'

    .col-sm-9
      = f.text_field :name, autofocus: true, value: @card.present? ? @card.cardholder_name : '',class: 'form-control input-lg'

      small= t('user.payments.as_it_appears_on_the_card')

  .form-group
    = f.label :card_number, t('user.payments.card_number'), class: 'col-sm-3 text-right'

    .col-sm-6
      = text_field_tag :payment_card_number, @card.present? ? @card.last_4.rjust(16, '*') : '', 'data-braintree-name'=> 'number', class: 'form-control input-lg', readonly: @card.present? ? true : false
      small= t('user.payments.sample_card_number')

    = f.label :cvv, t('user.payments.cvv'), class: 'col-sm-1 text-right'

    .col-sm-2
      = text_field_tag :payment_cvv, @card.present? ? '***' : '', 'data-braintree-name'=> 'cvv', class: 'form-control input-lg', readonly: @card.present? ? true : false

  .form-group
    = f.label :expiry_month, t('user.payments.expiry'), class: 'col-sm-3 text-right'

    .col-sm-4
      = select_month @card.present? ? @card.expiration_month.to_i : 14, { field_name: 'expiry_month', prefix: 'payment', use_two_digit_numbers: true },
        { autofocus: true, class: 'form-control input-lg', 'data-braintree-name' => 'expiration_month', disabled: @card.present? ? true : false}

    .col-sm-5
      = select_year Date.today, { field_name: 'expiry_year', prefix: 'payment', start_year: @card.present? ? @card.expiration_year.to_i : Time.now.year,
        end_year: (Time.now + 10.years).year }, { autofocus: true, class: 'form-control input-lg',
        'data-braintree-name' => 'expiration_year', disabled: @card.present? ? true : false }
      = hidden_field_tag :different_card, params[:different_card]

= f.fields_for :reservation do |reservation_form|
  = reservation_form.hidden_field :schedule
  - unless @new_payment_presenter.wing?
    = render partial: 'wing_quantity', locals: { reservation_form: reservation_form}

.form-group.not-hide
  .col-sm-3.hidden-xs &nbsp;
  .col-sm-9
    = render 'grouvly_info'

/- unless @new_payment_presenter.wing?
.form-group.not-hide
  .col-sm-3.hidden-xs &nbsp;

  .col-sm-9
    .text-center= f.label :voucher_code, t('user.payments.promotional_code'), class: 'mt-0'

    .row
      .col-xs-8
        = f.text_field :voucher_code, class: 'form-control input-lg'
        = hidden_field_tag :last_minute_booking, @new_payment_presenter.last_minute_booking

      .col-xs-4
        = f.submit t('user.payments.redeem'), class: 'btn btn-info btn-redeem'


.form-group.not-hide
  .col-sm-3.hidden-xs &nbsp;

  .col-sm-9
    - if @new_payment_presenter.fee == 0 && @new_payment_presenter.wing?
      = f.submit t('user.payments.continue'), class: 'btn btn-primary btn-lg width-100 btn-submit'
    - else
      = f.submit t('user.payments.securely_submit'), class: 'btn btn-primary btn-lg width-100 btn-submit'

app/views/user/payments/_grouvly_info.html.slim
p
  = check_box_tag 'condition_first'
  span.grouvly_info
    = t('user.payments.grouvly_info.first_pergraph')
p
  = check_box_tag 'condition_second'
  span.grouvly_info
    = t('user.payments.grouvly_info.second_pergraph')
p
  = check_box_tag 'condition_third'
  span.grouvly_info
    = t('user.payments.grouvly_info.third_pergraph')
p
  = check_box_tag 'condition_fourth'
  span.grouvly_info
    = t('user.payments.grouvly_info.fourth_paragraph')
p
  = check_box_tag 'condition_fifth'
  span.grouvly_info
    = t('user.payments.grouvly_info.fifth_paragraph')

app/views/user/payments/_heading.html.slim
h1= t('user.payments.confirm_your_grouvly')

.main-lead
  = t('user.payments.to_ensure_everyone_shows_up')

  | <br/>

  = t('user.payments.its_all_set_for', { date: @new_payment_presenter.reservation_date,
    time: @new_payment_presenter.reservation_time }).html_safe

- unless @new_payment_presenter.wing?
  #block-change-date= link_to t('user.payments.change_date'), new_user_reservation_path

- if current_user.valid_cards.present?
  -if params[:different_card].blank?
    #block-change-date= link_to t('user.payments.use_different_card'), new_user_payment_path(reservation: @new_payment_presenter.slug, different_card: "true")
  -else
    #block-change-date= link_to t('user.payments.use_saved_card'), new_user_payment_path(reservation: @new_payment_presenter.slug)

app/views/user/payments/_last_minute_booking_note.html.slim
#block-cancellation
  .col-sm-3.hidden-xs &nbsp;

  .col-sm-9.text-center
    h5.text-center= t('user.payments.last_minute_booking_policy')

    = t('user.payments.last_minute_booking_statement')

app/views/user/payments/_policies_block.html.slim
.block-policies
  h5= t('user.payments.policies')

  small= link_to t('terms.privacy_policy'), privacy_policy_path

  | <br/>

  small= link_to t('terms.terms_of_service'), terms_of_service_path 

app/views/user/payments/_questions_block.html.slim
.block-questions
  h5= t('user.payments.have_questions')

  small
    = image_tag 'icons/icon-email.png'
    | &nbsp;&nbsp;
    = APP_CONFIG['support_email']

app/views/user/payments/_secure_payment.html.slim
.block-secure-payment
  h5= t('user.payments.secure_payment') 

  span[id='siteseal']
    script[type='text/javascript' src='https://seal.godaddy.com/getSeal?sealID=eIuxPrLMzNJkUJHasSJeiTxDkReB8Ini9glv46N4yQ5eb6ySybMxQMoP']

app/views/user/payments/_ticket_description.html.slim
- gender = @new_payment_presenter.gender == "male" ? "men" : "women"
h4= t('user.payments.one_grouvly_ticket', gender: gender)

small= t('user.payments.what_this_covers')

| <br/>

-if @new_payment_presenter.last_minute_booking
  small= t('user.payments.last_minute_booking_fee_included').html_safe
-else
  small= t('user.payments.first_drink_included').html_safe

#block-price.center-block
  span#fee.fee= @new_payment_presenter.fee
  |&nbsp;
  span= @new_payment_presenter.currency

.block-card
  = image_tag 'visa.png'
  = image_tag 'mc.png'
  = image_tag 'ssl.png'

app/views/user/payments/_wing_quantity.html.slim
.form-group.not-hide
  .col-sm-3.hidden-xs &nbsp;
  .col-sm-12
    .row
      .text-center
        .col-xs-7.col-xs-offset-1
          = reservation_form.label :wing_quantity, t("user.reservations.wing_qunatity.select_wing_quantity"), class: 'mt-0'
        .col-xs-2
          =reservation_form.select(:wing_quantity, @new_payment_presenter.available_wing_quantity, {}, { :class => 'form-control btn-mini', "data-lead-fee" => @new_payment_presenter.fee, "data-wing-fee" => @new_payment_presenter.wing_fee })
        .co-xs-2
          = reservation_form.label :wing_quantity, t("user.reservations.wing_qunatity.#{@new_payment_presenter.gender}"), class: 'mt-0'

app/views/user/payments/new.html.slim
- content_for :title do
  = t('user.payments.payment')

script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"

- content_for :facebook_marketing do
  | <!-- Facebook Conversion Code for Payment with Facebook3 -->
  | <script>
  | (function() {
  | var _fbq = window._fbq || (window._fbq = []);
  | if (!_fbq.loaded) {
  | var fbds = document.createElement('script');
  | fbds.async = true;
  | fbds.src = '//connect.facebook.net/en_US/fbds.js';
  | var s = document.getElementsByTagName('script')[0];
  | s.parentNode.insertBefore(fbds, s);
  | _fbq.loaded = true;
  | }
  | })();
  | window._fbq = window._fbq || [];
  | window._fbq.push(['track', '6024297868532', {'value':'0.00','currency':'USD'}]);
  | </script>
  | <noscript>
  | <img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6024297868532&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" />
  | </noscript>

.row#block-expiration
  .container
    .col-sm-12
      span= t('user.payments.expiration')
      span.block-countdown

.background-gray
  .container
    .block-form.col-lg-12
      = render 'heading'

      .row.pt-20
        .col-md-7
          .visible-xs.block-sidebar= render 'ticket_description'

          = form_for(@new_payment_presenter.payment, url: user_payment_path, method: 'create',
            html: { role: 'form', class: 'form-horizontal', id: 'new_payment' }) do |f|

            - if @new_payment_presenter.has_credits? && @new_payment_presenter.voucher.blank?
              .form-group.block-credits-info
                .col-sm-3.hidden-xs &nbsp;

                .col-sm-9.text-center.mb-25
                  = t('user.payments.credits_available', { amount: @new_payment_presenter.available_credits,
                    currency: referral_currency })

                  | <br/>

                  strong= t('user.payments.credits_to_use', { amount: @new_payment_presenter.credits_to_use,
                    currency: referral_currency })

            - if @new_payment_presenter.payment.errors.any?
              .form-group
                .col-sm-3.hidden-xs &nbsp;

                .col-sm-9= error_messages!(@new_payment_presenter.payment)


            = render partial: 'form', locals: { f: f, presenter: @new_payment_presenter}

          -if @new_payment_presenter.last_minute_booking
            = render 'last_minute_booking_note'
          -else
            = render 'cancellation'

          .col-sm-3.hidden-xs &nbsp;

          .col-sm-9.text-center.highlight.block-address= APP_CONFIG['default_address']

        .col-md-5.clearfix
          .block-sidebar
            .hidden-xs= render 'ticket_description'

            hr.hidden-xs
            = render 'secure_payment'

            hr

            .row.pt-0
              .col-sm-7= render 'questions_block'

              .col-sm-5= render 'policies_block'