config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', via: [:get, :post]

  # match '/auth/admin/callback', to: 'sessions#authenticate_admin', as: :google_callback, via: [:get, :post]
  # match 'auth/facebook/callback', to: 'sessions#create', as: :facebook_callback, via: [:get, :post]
  match 'auth/failure', to: redirect('/why-facebook'), as: :facebook_failure, via: [:get, :post]
  match 'logout', to: 'sessions#destroy', via: [:get, :post]
  match 'about-us', to: 'pages#about_us', via: :get
  match 'bars-and-venues', to: 'pages#bars_and_venues', via: [:get, :post]
  match 'contact-us', to: 'pages#contact_us', via: [:get, :post]
  match 'faq', to: 'pages#faq', via: :get
  match 'how-it-works', to: 'pages#how_it_works', via: :get
  match 'press', to: 'pages#press', via: :get
  match 'privacy-policy', to: 'pages#privacy_policy', via: :get
  match 'terms-of-service', to: 'pages#terms_of_service', via: :get
  match 'why-facebook', to: 'pages#why_facebook', via: :get
  match 'r/:id', to: 'user/reservations#join', as: :join_reservation, via: :get
  match 'c/:id', to: 'pages#join', as: :join_referral, via: :get
  match 'venue/confirm', to: 'venues#confirm_booking', as: :venue_confirm_booking, via: :get
  match 'venue/reject', to: 'venues#reject_booking', as: :venue_reject_booking, via: :get

  match 'facebookprivatepilot', to: redirect('/'), via: :get

  get '/login', to: 'sessions#new', as: :new_user_login
  post '/login', to: 'sessions#create', as: :user_login

  namespace :admin do
    root to: 'admins#dashboard'

    resources :applicants, only: [:index, :show] do
      collection do
        get 'accept_selected'
        get 'reject_selected'
        get 'export_applicant'
      end
      member do
        get 'accept'
        post 'accept_member'
        get 'reject'
        post 'reject_member'
        get 'block'
        post 'block_member'
      end
    end

    resources :pools, only:[:index, :show, :create] do
      member do
        get 'possible_matches'
      end
      collection do
        get 'new_grouvly'
        post 'book_grouvly'
        post 'update_reservation_date'
      end
    end

    resources :reservations do
      collection do
        post 'capture_all_payments'
        post 'refund_amount'
      end
      member do
        get 'cancel_booking'
      end
    end

    resources :members, only: [:index, :show, :edit,:update] do
      member do
        post 'create_note'
      end
      collection do
        get 'search'
      end
    end

    resources :matches, only: [:index, :show] do
      member do
        post 'unmatch'
        post 'confirm_match'
      end
      collection do
        post 'book_venues', to: 'matches#book_venues'
        post 'notify_location', to: 'matches#notify_venue_location_details'
      end
    end

    resources :venues
    resources :vouchers
  end

  namespace :user do
    root to: 'users#dashboard'

    resource :membership, only: [:new, :create, :edit, :update] do
      member do
        get 'finish'
        get 'invite'
        get 'apply'
        patch 'submit_application'
      end
    end

    resources :reservations, only: [:new, :create] do
      member do
        get 'invite_wings'
        get 'confirmed'
        get 'roll'
        get 'refund_amount'
      end
      collection do
        post 'roll_confirmed'
        get 'venue/confirm/:id', to: 'reservations#confirm_venue_notification', as: :confirm_location
      end
    end

    resource :payment, only: [:new, :create] do
      member do
        post 'validate_voucher'
      end
    end
  end

  get 'admin/login', to: 'sessions#new_admin'
  post 'admin/login', to: 'sessions#admin_login'

  scope :location, as: :location do
    get 'countries', to: 'locations#countries'
    get 'neighborhoods', to: 'locations#neighborhoods'
  end

  constraints subdomain: :blog do
    get "*all", to: redirect { |params, req| "https://grouvly.com/blog/#{params[:all]}" }
  end

  get '/blog' => redirect('https://www.grouvly.com/blog/')

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: '/2kQ1VqsGzd'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/admin/pools_controller.rb
class Admin::PoolsController < Admin::AdminsController
  include Admin::Pools
  include Admin::Payments

  def index
    if params[:location]
      @presenter = ListPoolsPresenter.new({ location: params[:location] })
    else
      @presenter = ListPoolsPresenter.new
    end
  end

  def show
    @presenter = ShowPoolPresenter.new(params[:id], params[:date], params[:page])
    respond_to do |format|
      format.json { render json: @presenter.reservations_json }
      format.html
    end
  end

  def possible_matches
    render json: { matches: reservations_json, slug: params[:id] }
  end


  def new_grouvly
    if params[:submit].present?
      @users = User.by_email_and_name(params[:email], params[:name].split) if params[:name].present? || params[:email].present?      
      if @users.blank?
        flash.now[:error] = I18n.t('admin.pools.new_grouvly.no_record_found')
      end
    end
  end

  def book_grouvly
    @user = User.where(id: params[:user_id]).first
     BRAINTREE_LOGGER.info("user_id :: #{@user.id}")
    if @user.present? && @user.accepted?
      if new_reservation.save
        new_reservation.update_attribute(:last_minute_booking, true) if params[:last_minute_booking].present?
        @new_payment_presenter = NewPaymentPresenter.new(payment)
        set_other_payment_info
        if payment.save
          grouvly_date = DateTime.parse(params[:schedule]).strftime('%d %b %Y (%a) at %l:%M %p') if params[:schedule].present?
          if payment.status == "success"
            payment_processor = PaymentProcessor.new(payment.reservation)
            result = payment_processor.capture_all_payments
            if result == 0
              BRAINTREE_LOGGER.info("payment_captured :: user => #{@user.id}, amount => #{payment.amount} ")
              payment.reservation.enter_payment! if payment.reservation.user == @user

              BRAINTREE_LOGGER.info("payment :: #{payment.inspect}, payment_status:: success, payment_result: #{result}")
              send_emails
              flash.now[:notice] = I18n.t('admin.pools.new_grouvly.create_reservation', user_name: @user.name, date: grouvly_date)
            else
              payment_error(payment, @user, result)
            end
          elsif payment.status == "pending"
            payment.reservation.pending_peyment! if payment.reservation.user == @user

            send_emails

            BRAINTREE_LOGGER.info("payment :: #{payment.inspect}, payment_status:: pending")

            flash.now[:notice] = I18n.t('admin.pools.new_grouvly.pending_reservation', user_name: @user.name, date: grouvly_date)
          end
        else
          payment_error(payment, @user, "payment_obj_not_saved")
        end
      else
        flash.now[:error] = @reservation.errors.full_messages.join(", ")
      end
    else
      BRAINTREE_LOGGER.info("user_id :: user_unavailable")
      flash.now[:error] = I18n.t('admin.pools.new_grouvly.user_unavailable')
    end
    render :new_grouvly
  end

  def update_reservation_date
    if params["move_reservaton_ids"].present?
      errors = ""
      error_message = ""
      reservation_ids = params["move_reservaton_ids"].split(",").uniq
      reservation_ids.each do |id|
        reservation = Reservation.where(slug: id).first
        unless reservation.update_attributes(schedule: params[:available_date], user_type: "admin")
          reservation.errors.messages.each {|key, value| error_message = value}
          errors << reservation.user.name + "::  #{error_message.first} "
        end
      end
      if errors.present?
        notification = { error:  errors}
      else
        date = DateTime.parse(params[:available_date]).strftime('%d %b %Y (%a) at %l:%M %p')
        notification = { notice:  I18n.t('admin.pools.show.moved_successfully', date: date) }
      end
    else
      notification = { error:  I18n.t('admin.pools.show.please_select_reservations') }
    end
    redirect_to admin_pool_path({id: params[:location_id], date: params[:date] }), flash: notification
  end

  def create
    if first_reservation && second_reservation && first_reservation != second_reservation
      if previously_matched?
        notification = { error: I18n.t('admin.pools.show.previously_matched') }
      else
        matched_reservation.first_reservation_id = first_reservation.id
        matched_reservation.second_reservation_id = second_reservation.id
        matched_reservation.schedule = first_reservation.schedule

        # if graph.get_connections("me", "friends/#{second_reservation.user.uid}").present?
        #   notification = { error: I18n.t('admin.pools.show.already_friends_in_facebook') }
        # elsif matched_reservation.save
        #   matched_reservation.new!(current_admin)
        #   notification = { notice: I18n.t('admin.pools.show.matched_successfully') }
        # else
        #   notification = { error: I18n.t('admin.pools.show.matched_wrongfully') }
        # end

        if matched_reservation.save
          matched_reservation.new!(current_admin)
          notification = { notice: I18n.t('admin.pools.show.matched_successfully') }
        else
          notification = { error: I18n.t('admin.pools.show.matched_wrongfully') }
        end
      end
    else
      notification = { error: I18n.t('admin.pools.show.matched_wrongfully') }
    end
    redirect_to admin_pool_path(user_location, { date: schedule }), flash: notification
  end
end

private

def payment_error(payment, user, result)
  payment.update_attribute(:status, 'error')
  BRAINTREE_LOGGER.info("payment :: #{payment.inspect}, payment_status:: error, payment_errors :: #{payment.errors.full_messages}, payment_result: #{result}")

  if user.errors.any?
    edit_profile_path = "#{request.protocol}#{request.host_with_port}#{edit_admin_member_path(user.id)}"
    flash.now[:error] = I18n.t('admin.pools.new_grouvly.incomplete_profile', edit_profile_url: edit_profile_path)
  else
    flash.now[:error] = I18n.t('admin.pools.new_grouvly.we_cannot_process_your_card', user_name: user.name)
  end
end

app/controllers/concerns/admin/pools.rb
module Admin::Pools
  extend ActiveSupport::Concern

  def first_reservation
    @first_reservation ||= Reservation.where(slug: params[:first_reservation_id]).first
  end

  def second_reservation
    @second_reservation ||= Reservation.where(slug: params[:second_reservation_id]).first
  end

  def previously_matched?
    MatchedReservation.find_each do |matched_reservation|
      if matched_reservation.current_state != "unmatched" && matched_reservation.first_reservation.present? && matched_reservation.second_reservation.present?
       user_arr = [matched_reservation.first_reservation.user.id, matched_reservation.second_reservation.user.id]
       new_matched_arr = [first_reservation.user.id, second_reservation.user.id]
       return true if user_arr.sort == new_matched_arr.sort
      end
    end
  end

  def schedule
    @schedule ||= first_reservation.schedule
  end

  def user_location
    @location ||= first_reservation.user.location
  end

  def matched_reservation
    @matched_reservation ||= MatchedReservation.new
  end

  def reservations_json
    (ActiveModel::ArraySerializer.new(reservations, each_serializer: ::ReservationSerializer))
  end

  def graph
    @graph ||= Koala::Facebook::API.new(first_reservation.user.oauth_token)
  end

  private

  def reservation
    @reservation ||= Reservation.where(slug: params[:id]).first
  end

  def reservations
    @reservations ||= Reservation.find_by_location_gender_and_schedule(reservation).unmatched.page(params[:page])
  end
end

app/views/admin/pools/_last_minute_booking.html.slim
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Express fee
      .modal-body
        = form_tag book_grouvly_admin_pools_path, method: :post, class: 'form-horizontal'
          = hidden_field_tag :user_id
          = hidden_field_tag :schedule
          .row
            .col-md-12
              .col-md-4
                =label_tag t("admin.pools.new_grouvly.express_fee"), nil, class: 'checkbox_container_label'
              .col-md-8
                =check_box_tag :last_minute_booking

          .modal-footer
            = submit_tag( t('admin.pools.new_grouvly.book_btn'), name: 'submit',class: 'btn btn-primary')

app/views/admin/pools/_member_list.html.slim
h4=t('admin.pools.new_grouvly.members')

table.table.table-bordered
  thead
    tr
      th.text-uppercase= t('admin.pools.new_grouvly.name')
      th.text-uppercase= t('admin.pools.new_grouvly.email')
      th.text-uppercase= t('admin.pools.new_grouvly.available_dates')
      th.text-uppercase= t('admin.pools.new_grouvly.action')

  tbody
    -@users.each do |user|
      tr
        td
          = link_to user.name, admin_member_path(user.id)
        td
          = user.email_address
          = hidden_field_tag :lead_user_id, user.id
        td
          - reservation = get_reservation(user, params[:schedule])
          -if reservation.present?
            = select_tag 'reservation_schedule', options_for_select(reservation.admin_available_dates, params[:schedule]), prompt: t('admin.pools.new_grouvly.available_date_label'),class: 'input-lg form-control', id: "reservation_schedule_#{user.id}",  data: { id: user.id}, onclick: 'grouvlyBooking($(this));'

        td
          = submit_tag( t('admin.pools.new_grouvly.book_btn'), name: 'submit', id: "grouvly_booking_btn_#{user.id}", "data-toggle" => "modal", "data-target" => "#myModal",class: 'btn btn-primary disabled')

= render "last_minute_booking"

app/views/admin/pools/index.html.slim
header.content-header-block
  .row
    .action-block.col-sm-12
      = link_to t('admin.pools.new_grouvly.book_new_grouvly'), new_grouvly_admin_pools_path,
        class: 'btn btn-primary pull-right'

.block-content
  .row
    .container-fluid
      .col-md-12
        h1= "#{@presenter.location} #{t('admin.pools.index.pools')}"

        table.table.table-bordered
          thead
            tr
              th
                = link_to admin_pools_path do
                  = icon('chevron-left')
                  = t('admin.pools.index.all_pools')
              th.text-uppercase= t('admin.pools.index.free_guys')
              th.text-uppercase= t('admin.pools.index.free_girls')
              th.text-uppercase= t('admin.pools.index.matches')

          tbody
            - @presenter.pools.each do |pool|
              tr
                td.text-left
                  - if @presenter.location
                    /= link_to "#{pool[:date][1].strftime('%d %b %Y (%a) at %l:%M %p')}",
                      /admin_pool_path({ id: pool[:location], date: pool[:date][1] })
                    = link_to "#{pool[:date].strftime('%d %b %Y (%a) at %l:%M %p')}",
                      admin_pool_path({ id: pool[:location], date: pool[:date] })
                  - else
                    = link_to pool[:location], admin_pools_path({ location: pool[:location] })

                td= pool[:free_guys]
                td= pool[:free_girls]
                td= pool[:matched]

            tr.background-gray
              td
              td= @presenter.total_free_guys
              td= @presenter.total_free_girls
              td= @presenter.total_matches

app/views/admin/pools/new_grouvly.html.slim
= render partial: 'admin/shared/flash_messages'

header.content-header-block
  .row
    .title-block.col-sm-8
      h1
        span= t('admin.terms.grouvly')
        small= t('admin.terms.bookings')

.block-content
  .row
    .container-fluid
      .block-search-filter.clearfix
        .col-md-12
          = form_tag new_grouvly_admin_pools_path, method: :get, class: 'form-horizontal col-xs-12'
            .row
              .col-md-6
                .form-group-lg
                  = label_tag :name, t('admin.pools.new_grouvly.name_label'),
                class: 'col-md-4 control-label'

                  .col-md-8
                    = text_field_tag :name, params[:name], class: 'form-control'
              .col-md-6
                .form-group-lg
                  = label_tag :email, t('admin.pools.new_grouvly.email_label'),
                class: 'col-md-4 control-label'

                  .col-md-8
                    = text_field_tag :email, params[:email], autofocus: true, class: 'form-control datepicker'
            .row
              .col-md-6
                .form-group-lg
                  .col-md-8.col-md-offset-4
                    = submit_tag( t('admin.pools.new_grouvly.search_btn'), name: 'submit', id: 'grouvly_search_btn', class: 'btn btn-primary')
-if @users.present?
  .block-content
    .row
      .container-fluid
        .block-search-filter.clearfix
          .col-md-12
            = render "member_list"

app/views/admin/pools/show.html.slim
= render partial: 'admin/shared/flash_messages'

#block-move-to-pool.block-content.clearfix
  .row
    .container-fluid
      .col-md-6
        = form_tag update_reservation_date_admin_pools_path, method: :post do
          = hidden_field_tag :date, params[:date]
          = hidden_field_tag :location_id, params[:id]
          = hidden_field_tag :move_reservaton_ids, id: "move_reservation_ids"
          .col-md-8
            = select_tag 'available_date', options_for_select(@presenter.all_available_dates(params[:date])), prompt: t('admin.pools.show.move_to'),class: 'input-lg form-control', onchange: 'onChange();'

          .col-md-4
            .pull-right
              = submit_tag t('admin.pools.show.confirm'), class: 'btn btn-primary confirm-move-to disabled', :onclick => "getReservationIds();"

      - if params[:date].present?
        .col-md-6
          .pull-right
            .admin_schedule_date
              =params[:date].to_datetime.strftime('%d %b %Y (%a) at %l:%M %p')

#block-chosen-pool.block-content.clearfix.hidden
  .row
    .container-fluid
      #block-chosen-first.col-md-6
      #block-chosen-second.col-md-6

  #block-match-button.row
    .container-fluid
      .col-md-12
        = form_tag admin_pools_path, method: :post do
          = hidden_field_tag :first_reservation_id
          = hidden_field_tag :second_reservation_id

          .pull-right
            = submit_tag t('admin.pools.show.temp_match'), class: 'btn btn-primary btn-confirm-match disabled'

#block-reservation-pool.block-content.clearfix
  .row
    .container-fluid
      .col-md-6
        #block-match-first

        #block-reserved-users-first

        #block-pagination-first.hidden= paginate @presenter.reservations

      .col-md-6
        #block-match-second

        #block-reserved-users-second

        #block-pagination-second.hidden= paginate @presenter.reservations, params: { controller: 'pools',
          action: 'possible_matches', id: 'id-here', date: nil }

  script[id='ReservationsData' type='application/json']
    = raw @presenter.reservations_json